package com.cdivtc.model;

import java.io.Serializable;

public class CClass implements Serializable{

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_class.c_id
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    private String cId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_class.c_name
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    private String cName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_class.c_id
     *
     * @return the value of c_class.c_id
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    public String getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_class.c_id
     *
     * @param cId the value for c_class.c_id
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    public void setcId(String cId) {
        this.cId = cId == null ? null : cId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_class.c_name
     *
     * @return the value of c_class.c_name
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    public String getcName() {
        return cName;
    }

    @Override
    public String toString() {
        return "CClass{" +
                "cId='" + cId + '\'' +
                ", cName='" + cName + '\'' +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_class.c_name
     *
     * @param cName the value for c_class.c_name
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     *
     */

    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }
}