package com.cdivtc.model;

import java.io.Serializable;

public class CrClassReport implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_class_report.cr_id
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    private String crId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_class_report.cr_teacher
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    private String crTeacher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_class_report.cr_date
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    private String crDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_class_report.cr_week
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    private String crWeek;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_class_report.cr_time
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    private String crTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_class_report.cr_class
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    private String crClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_class_report.cr_class_room
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    private String crClassRoom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_class_report.cr_couse_num
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    private Integer crCouseNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_class_report.cr_remarks
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    private String crRemarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_class_report.cr_flag
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    private Integer crFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_class_report.cr_duty
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    private Integer crDuty;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_class_report.cr_id
     *
     * @return the value of cr_class_report.cr_id
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    public String getCrId() {
        return crId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_class_report.cr_id
     *
     * @param crId the value for cr_class_report.cr_id
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    public void setCrId(String crId) {
        this.crId = crId == null ? null : crId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_class_report.cr_teacher
     *
     * @return the value of cr_class_report.cr_teacher
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    public String getCrTeacher() {
        return crTeacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_class_report.cr_teacher
     *
     * @param crTeacher the value for cr_class_report.cr_teacher
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    public void setCrTeacher(String crTeacher) {
        this.crTeacher = crTeacher == null ? null : crTeacher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_class_report.cr_date
     *
     * @return the value of cr_class_report.cr_date
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    public String getCrDate() {
        return crDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_class_report.cr_date
     *
     * @param crDate the value for cr_class_report.cr_date
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    public void setCrDate(String crDate) {
        this.crDate = crDate == null ? null : crDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_class_report.cr_week
     *
     * @return the value of cr_class_report.cr_week
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    public String getCrWeek() {
        return crWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_class_report.cr_week
     *
     * @param crWeek the value for cr_class_report.cr_week
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    public void setCrWeek(String crWeek) {
        this.crWeek = crWeek == null ? null : crWeek.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_class_report.cr_time
     *
     * @return the value of cr_class_report.cr_time
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    public String getCrTime() {
        return crTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_class_report.cr_time
     *
     * @param crTime the value for cr_class_report.cr_time
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    public void setCrTime(String crTime) {
        this.crTime = crTime == null ? null : crTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_class_report.cr_class
     *
     * @return the value of cr_class_report.cr_class
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    public String getCrClass() {
        return crClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_class_report.cr_class
     *
     * @param crClass the value for cr_class_report.cr_class
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    public void setCrClass(String crClass) {
        this.crClass = crClass == null ? null : crClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_class_report.cr_class_room
     *
     * @return the value of cr_class_report.cr_class_room
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    public String getCrClassRoom() {
        return crClassRoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_class_report.cr_class_room
     *
     * @param crClassRoom the value for cr_class_report.cr_class_room
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    public void setCrClassRoom(String crClassRoom) {
        this.crClassRoom = crClassRoom == null ? null : crClassRoom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_class_report.cr_couse_num
     *
     * @return the value of cr_class_report.cr_couse_num
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    public Integer getCrCouseNum() {
        return crCouseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_class_report.cr_couse_num
     *
     * @param crCouseNum the value for cr_class_report.cr_couse_num
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    public void setCrCouseNum(Integer crCouseNum) {
        this.crCouseNum = crCouseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_class_report.cr_remarks
     *
     * @return the value of cr_class_report.cr_remarks
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    public String getCrRemarks() {
        return crRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_class_report.cr_remarks
     *
     * @param crRemarks the value for cr_class_report.cr_remarks
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    public void setCrRemarks(String crRemarks) {
        this.crRemarks = crRemarks == null ? null : crRemarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_class_report.cr_flag
     *
     * @return the value of cr_class_report.cr_flag
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    public Integer getCrFlag() {
        return crFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_class_report.cr_flag
     *
     * @param crFlag the value for cr_class_report.cr_flag
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    public void setCrFlag(Integer crFlag) {
        this.crFlag = crFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_class_report.cr_duty
     *
     * @return the value of cr_class_report.cr_duty
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    public Integer getCrDuty() {
        return crDuty;
    }

    @Override
    public String toString() {
        return "CrClassReport{" +
                "crId='" + crId + '\'' +
                ", crTeacher='" + crTeacher + '\'' +
                ", crDate='" + crDate + '\'' +
                ", crWeek='" + crWeek + '\'' +
                ", crTime='" + crTime + '\'' +
                ", crClass='" + crClass + '\'' +
                ", crClassRoom='" + crClassRoom + '\'' +
                ", crCouseNum=" + crCouseNum +
                ", crRemarks='" + crRemarks + '\'' +
                ", crFlag=" + crFlag +
                ", crDuty=" + crDuty +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_class_report.cr_duty
     *
     * @param crDuty the value for cr_class_report.cr_duty
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    public void setCrDuty(Integer crDuty) {
        this.crDuty = crDuty;
    }
}