package com.cdivtc.model;

public class CtClassTime {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_class_time.ct_id
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    private String ctId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ct_class_time.ct_time
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    private String ctTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_class_time.ct_id
     *
     * @return the value of ct_class_time.ct_id
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    public String getCtId() {
        return ctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_class_time.ct_id
     *
     * @param ctId the value for ct_class_time.ct_id
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    public void setCtId(String ctId) {
        this.ctId = ctId == null ? null : ctId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ct_class_time.ct_time
     *
     * @return the value of ct_class_time.ct_time
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    public String getCtTime() {
        return ctTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ct_class_time.ct_time
     *
     * @param ctTime the value for ct_class_time.ct_time
     *
     * @mbggenerated Mon Oct 21 11:11:06 CST 2019
     */
    public void setCtTime(String ctTime) {
        this.ctTime = ctTime == null ? null : ctTime.trim();
    }
}