package com.cdivtc.model;

import java.io.Serializable;

public class UUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.u_id
     *
     * @mbggenerated Mon Oct 21 11:13:40 CST 2019
     */
    private String uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.u_username
     *
     * @mbggenerated Mon Oct 21 11:13:40 CST 2019
     */
    private String uUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.u_password
     *
     * @mbggenerated Mon Oct 21 11:13:40 CST 2019
     */
    private String uPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.u_name
     *
     * @mbggenerated Mon Oct 21 11:13:40 CST 2019
     */
    private String uName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.u_img
     *
     * @mbggenerated Mon Oct 21 11:13:40 CST 2019
     */
    private String uImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.u_flag
     *
     * @mbggenerated Mon Oct 21 11:13:40 CST 2019
     */
    private Integer uFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user.u_course
     *
     * @mbggenerated Mon Oct 21 11:13:40 CST 2019
     */
    private String uCourse;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.u_id
     *
     * @return the value of u_user.u_id
     *
     * @mbggenerated Mon Oct 21 11:13:40 CST 2019
     */
    public String getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.u_id
     *
     * @param uId the value for u_user.u_id
     *
     * @mbggenerated Mon Oct 21 11:13:40 CST 2019
     */
    public void setuId(String uId) {
        this.uId = uId == null ? null : uId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.u_username
     *
     * @return the value of u_user.u_username
     *
     * @mbggenerated Mon Oct 21 11:13:40 CST 2019
     */
    public String getuUsername() {
        return uUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.u_username
     *
     * @param uUsername the value for u_user.u_username
     *
     * @mbggenerated Mon Oct 21 11:13:40 CST 2019
     */
    public void setuUsername(String uUsername) {
        this.uUsername = uUsername == null ? null : uUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.u_password
     *
     * @return the value of u_user.u_password
     *
     * @mbggenerated Mon Oct 21 11:13:40 CST 2019
     */
    public String getuPassword() {
        return uPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.u_password
     *
     * @param uPassword the value for u_user.u_password
     *
     * @mbggenerated Mon Oct 21 11:13:40 CST 2019
     */
    public void setuPassword(String uPassword) {
        this.uPassword = uPassword == null ? null : uPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.u_name
     *
     * @return the value of u_user.u_name
     *
     * @mbggenerated Mon Oct 21 11:13:40 CST 2019
     */
    public String getuName() {
        return uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.u_name
     *
     * @param uName the value for u_user.u_name
     *
     * @mbggenerated Mon Oct 21 11:13:40 CST 2019
     */
    public void setuName(String uName) {
        this.uName = uName == null ? null : uName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.u_img
     *
     * @return the value of u_user.u_img
     *
     * @mbggenerated Mon Oct 21 11:13:40 CST 2019
     */
    public String getuImg() {
        return uImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.u_img
     *
     * @param uImg the value for u_user.u_img
     *
     * @mbggenerated Mon Oct 21 11:13:40 CST 2019
     */
    public void setuImg(String uImg) {
        this.uImg = uImg == null ? null : uImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.u_flag
     *
     * @return the value of u_user.u_flag
     *
     * @mbggenerated Mon Oct 21 11:13:40 CST 2019
     */
    public Integer getuFlag() {
        return uFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.u_flag
     *
     * @param uFlag the value for u_user.u_flag
     *
     * @mbggenerated Mon Oct 21 11:13:40 CST 2019
     */
    public void setuFlag(Integer uFlag) {
        this.uFlag = uFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user.u_course
     *
     * @return the value of u_user.u_course
     *
     * @mbggenerated Mon Oct 21 11:13:40 CST 2019
     */
    public String getuCourse() {
        return uCourse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user.u_course
     *
     * @param uCourse the value for u_user.u_course
     *
     * @mbggenerated Mon Oct 21 11:13:40 CST 2019
     */
    public void setuCourse(String uCourse) {
        this.uCourse = uCourse == null ? null : uCourse.trim();
    }

    @Override
    public String toString() {
        return "UUser{" +
                "uId='" + uId + '\'' +
                ", uUsername='" + uUsername + '\'' +
                ", uPassword='" + uPassword + '\'' +
                ", uName='" + uName + '\'' +
                ", uImg='" + uImg + '\'' +
                ", uFlag=" + uFlag +
                ", uCourse='" + uCourse + '\'' +
                '}';
    }
}